services:
  mc-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 25566:25565
    volumes:
      - mc-server:/server
volumes:
  mc-server:
