services:
  mc-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 25566:25565
    environment:
      - DEBUG_COLORS:"true"
      - TERM:"xterm-256color"
      - COLORTERM:"truecolor"
    volumes:
      - mc-server:/server-data
  #backup-endpoint:
  #  image: rclone/rclone:latest
  #  #command: serve restic
  #  volumes:
  #    - mc-server:/data
  #    - ~/.config/rclone:/config/rclone

volumes:
  mc-server:
